### ISSUE TITLE
Help me make the deal section 

### ISSUE THREAD

**Issue by DucTranNFQ** [DucTranNFQ/orgik-shopify#1]
Hello everyone, Can you help me make a deal section. 

Link to theme:
https://orgik-theme.myshopify.com/
Password: buddha

On mobile like this:
![Screenshot from 2022-05-19 10-31-51](https://user-images.githubusercontent.com/104955715/169198561-8a7c5c00-d1ad-4dad-8073-58e9b23380b3.png)

On desktop like this:
![Screenshot from 2022-05-19 10-27-46](https://user-images.githubusercontent.com/104955715/169198468-12371f56-62cb-47ad-80db-26ed13ec64b3.png)

**Comment by zevik7** [comment]
Ok, I will create a pull request soon

**Comment by DucTranNFQ** [comment]
Okay, thank you very much!
